<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OpenDeviceToolkit.Android</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenDeviceToolkit.Core\OpenDeviceToolkit.Core.csproj" />
  </ItemGroup>
</Project>
