<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>true</WarningsAsErrors>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Company>OpenDeviceToolkit</Company>
    <Copyright>Copyright © 2026</Copyright>
    <Version>0.1.0</Version>
    <OutputType>Exe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenDeviceToolkit.Core\OpenDeviceToolkit.Core.csproj" />
    <ProjectReference Include="..\OpenDeviceToolkit.Android\OpenDeviceToolkit.Android.csproj" />
    <ProjectReference Include="..\OpenDeviceToolkit.Hardware\OpenDeviceToolkit.Hardware.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Speech" />
  </ItemGroup>

</Project>
